name: jasyrin_soz
description: Қазақша жасырын сөз ойыны (Flutter)
publish_to: "none"
version: 1.0.0+13

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1   # ⬅️ 6.x емес

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/words_kk.json
    - assets/sfx/correct.wav
    - assets/sfx/near.wav
    - assets/sfx/wrong.wav
